version: "3.7"
services:
  client-user:
    build:
      context: ./client-user
      dockerfile: ./Dockerfile
    ports:
      - "80:8080"
    networks:
      - war-network
    depends_on:
      - wsserver

  client-cli:
    build:
      context: ./client-cli
      dockerfile: ./Dockerfile
    environment:
      - "URL=ws://wsserver:9999"
    networks:
      - war-network
    depends_on:
      - wsserver
  
  wsserver:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "9999:9999"
    networks:
      - war-network

networks:
  war-network: